### ISSUE TITLE
Jira Software + GitHub Enterprise + Bulldozer

### ISSUE THREAD

**Issue by phnakarin** [integrations/jira#291] opened 2019-10-21 08:01 UTC
Hello there,

We bump into an issue with Jira Software when a bot user like Bulldozer updating or merging PR.

We are a GitHub Enterprise + Jira Software + Bulldozer bot (https://github.com/palantir/bulldozer\) user. We use Bulldozer for automatically merging and updating PRs if all checks passed, triggering by GitHub labels.

Our problem is when the PRs are done with Bulldozer. The PR statuses don't change. They have been left in an OPEN state. It doesn't happen when normal GitHub users do that. We try to find out what happens but end up we don't know what we are doing. It is better to talk to someone who can shred us some light the way Jira Software does recognise a change.

We suspected something around a user and bot type. We could not create a Jira user to be exactly the same as Bulldozer login, for example, `bulldozer[bot]` as `[]` doesn't permit in an email address. We realised that the `[bot]` suffix is added automatically by GitHub to distinguish normal users from users that are associated with a GitHub App.

Is it a known issue? Has anyone experienced this so far?

**Comment by fclairamb** [comment] 2020-01-31 14:21
We do exactly the same thing at @habx and this is a major issue. Most of our pull-requests are now automatically merged (once updated with the base branch and passing the CI), and they all stay in the "OPEN" state. 
This is a big issue, please fix it.

**Comment by clementlecorre** [comment] 2020-02-24 17:05
up!

**Comment by fclairamb** [comment] 2020-03-05 01:29
@zmoazeni can you please have a look at this?

We're progressively doing most of our merges through bots and this is creating a clear disconnect between the repo state and what JIRA sees of the repo. In other words, your integration is currently reporting a bad state, which makes it look like it's broken.

Is there any good reason for doing this? Bots are definitely a valid reason to handle pull-requests merges and this is integration is currently making it a pain for developers of my team.

**Comment by zmoazeni** [comment] 2020-03-05 15:37
@fclairamb This has already been added to our list to prioritize. Unfortunately it not at the top of the list. I appreciate this is a pain point for you and your team, but pinging contributors to this repository does not increase its priority.

**Comment by brantburnett** [comment] 2020-06-30 12:49
I understand and appreciate that lots of comments from lots of people don't necessarily help. But I'd like to point out that this is, in my opinion, not a missing feature but a regression. The previous form of JIRA/GitHub integration handled merges performed by bots just fine. We switched to this new integration per the direction of JIRA, and now this is broken. Please take this into account in your prioritizations.

Also, the fix itself seems relatively simple. I'm certainly open to putting in a PR to fix it myself, assuming that's something that JIRA is open to accepting. Also, assuming that accepting stuff from bots doesn't have unanticipated side-effects (I'm assuming it was blocked originally for some reason). In the worst case, it seems like we could pay attention to merges from bots and ignore other things.

If this is something acceptable for me to do, please let me know. I'm happy to help.

**Comment by zmoazeni** [comment] 2020-07-14 13:33
I don't think anyone has shared the issues were trying to resolve on the engineering side for this concern. If not, I'll try and summarize.

The main issue is that the Jira integration itself is a "bot". And we don't a single bot's action (like adding a comment) to trigger a webhook delivery storm because the organization has several bots that happen to be interacting with each other.

I believe there need to be some additional UI to help direct the user to understand the intent in that case. Rather than this entirely being a code solution.

**Comment by brantburnett** [comment] 2020-07-14 13:41
@zmoazeni 

I definitely understand your point as regards comments. I.e. if two bots are both set to auto-respond to all comments, you'd get an infinite loop. And there are probably many other, subtler cases.

However, I'd argue that the act of merging (which is inherently a one-time action) is an exception that is causing significant problems. I don't see what the bot-filter couldn't be dropped for merge hooks, but left in place for other types of hooks, so that the status could be properly posted in JIRA.

**Comment by zmoazeni** [comment] 2020-07-16 21:53
> However, I'd argue that the act of merging (which is inherently a one-time action) is an exception that is causing significant problems. I don't see why the bot-filter couldn't be dropped for merge hooks, but left in place for other types of hooks, so that the status could be properly posted in JIRA.

@brantburnett Thank you for that perspective and thank you for sharing this 🙏 . One thing that would really help my team with this effort is if someone can put together a list of actions that we think could be above this line (processed like normal) and what should clearly below the line (ignored).

I'm asking that because this particular effort within the Jira integration is much lower priority compared to other things we're working on within GitHub. If you all could help us figure out what _should_ be done here, in a way that won't negatively impact any of the customers who are currently fine with the existing logic. That would go a long long way.

My main concern here is to avoid causing issues with the large segment of users who don't have this need. If you all can help me with that, that can end up as a win-win-win.

---

One UI thought I have is simply just allowing users to determine if _any_ bot activity is ignored. Like a two way toggle switch with the existing behavior being one of of those states.

At least we could change the existing situation so you all could enable bot webhook requests, while also being mindful that other things may break. And if they do, we can try and address them one by one.

That may also be a way to slow-roll an experimental logic branch that we're talking about here. So you all could benefit AND help us keep it stable.

❤️

**Comment by brantburnett** [comment] 2020-07-17 12:13
For our purposes, your proposed UI toggle would work. We're not doing anything with bots in our system that would cause a storm, I don't think. It's a good idea for a way to organize a safe experiment.

Also, here is a list of my thoughts on various `pull_request` actions. The focus here is on handling actions which related to that information kept "synchronized" in JIRA and displayed on the UI. Ignoring those actions means that the information becomes incorrect.

| Action | Handle from Bot? | Notes |
| ------ | -------- | ----- |
| opened | ? | How are PRs opened by bots like GitHub's dependabot handled? |
| edited | Y | To get any updates to the PR description |
| closed | Y | This covers closing both with and without merging |
| assigned | | |
| unassigned | | |
| review_requested | | Left off because I don't think review status is supported for GitHub yet |
| review_request_removed | | Left off because I don't think review status is supported for GitHub yet |
| ready_for_review | | |
| labeled | | |
| unlabeled | | |
| synchronize | | |
| locked | | |
| unlocked | | |
| reopened | Y | |

Again, I know this may not be high on the Atlassian priority list, but it is high on mine. So if I can help with a PR or other work in any way, please let me know.

**Comment by zmoazeni** [comment] 2020-07-17 21:21
@brantburnett I love your work here. I'm not with Atlassian. I'm with GitHub, but I like the way you're laying it out here.

What I would like to do is ask for other folks who have participated in this thread and are also motivated to get this changed to help us refine what you started. Is EVERYONE in agreement? Can you all help me by playing devil's advocate to try and figure out if these scenarios would break any customers if we didn't implement a toggle?

Should...we....ship a hidden UI toggle? Like a beta opt-in feature so you all can experiment with the ramifications and then over time we can gain enough confidence to roll this out installation-wide?

What would help me right now is to lean on everyone motivated in this thread to give me the confidence by listing out the ways this can go wrong so we can mitigate that. I'll be honest, I just don't have it at the moment. But I have more than I did last week. And that's due to this conversation and everyone work so far in this thread.

The PR itself is the easy work. The hard work is what you're doing. I appreciate that very very much. 🙏 

Once I have my head wrapped around the what change we're going to make and the ramifications, I can take this to the folks internally at GitHub to get a 👍 to just roll forward, even though this is not a high priority for us at the moment. The more we protect the vast majority of users who don't have this need from experiencing issues or suddenly spiking support tickets, the easier it is to get that +1 and just knock out a PR to deploy.

**Comment by zmoazeni** [comment] 2020-08-13 11:45
Hey folks. I know this is top of mind for a few customers. I just want to make sure to bump this thread to have you all help us internally.

I want to be clear, this is still not on our immediate priority roadmap. And my team can't move forward on it until it's closer to the top of that list. That may change, but I would wager that unlikely any time soon.

* @brantburnett how confident are you that plan above will not affect any of our existing customers using this integration? 
* Are there any options we can ship with to help **us** (you all AND us internally) gain that confidence in production?
* Can anyone else who has participated (or not) help @brantburnett with the implementation plan?

**Comment by Raul6469** [comment] 2021-02-02 17:48
Hey there! 👋 

I'm bumping this up to see if there are any internal updates about this issue. I'm being affected by this restriction on bots events as well, and I am ok to work on this if needed.

I understand the concern about infinite event webhooks, but having an exception **only on PR state changes** looks good to me. I don't see how we can end up in such a situation if we allow bot events processing only for those, given the fact that this integration does not update PR states by itself.

To me, the infinite loop issue may only happen on comment / description edition, because it is the only case where this Jira integration actually writes data in GitHub and can trigger events.

WDYT? @zmoazeni @brantburnett

**Comment by atrigueiro** [comment] 2021-05-14 06:38
Hi all,

we've fixed this bug and it's now out in prod! https://github.com/integrations/jira/pull/437

**Closed by atrigueiro** 2021-05-14 06:38 UTC
