### ISSUE TITLE
Pull request is not linked when title is edited

### ISSUE THREAD

**Issue by lukasnovy** [integrations/jira#383] opened 2020-08-24 15:08 UTC
Hi,
I've a pull request with some initial title (without jira ticket). Later ticket is created and I edit PR label to contain that ticket number. But jira is not detecting that Pull request. 

I believe that pull request integration with jira is not triggered when title is edited, probably only when PR is created.

**Comment by Nitori-** [comment] 2020-12-15 19:34
We this this behavior as well.

A workaround is to close and reopen the PR after changing the title. However, this can cause other workflow problems, so a proper fix would be ideal.

**Comment by rachellerathbone** [comment] 2021-05-17 10:40
Hi @lukasnovy and @Nitori-. I'm from a team at Atlassian that is currently in the process of migrating the ownership over to us from GitHub. As a part of this, we're currently going through the backlog of issues and prs to see what can still be addressed and what should be closed.

Can you both please let me know if this is still an issue for either of you so I can follow up?

**Comment by Nitori-** [comment] 2021-05-17 13:51
Hi @rachellerathbone !

I just verified that this is indeed still an issue for us.

Steps to reproduce:

- Setup JIRA-GHE integration
- Open a PR without mentioning a JIRA ID in the title
- Edit the title of the PR to mention a JIRA ID
- No association will be made on the JIRA side
- Close and re-open the PR and it will register in JIRA (not a desirable requirement, but it works as a crude workaround)

GHE version: 3.0.2
JIRA version: 8.5.4

**Comment by rachellerathbone** [comment] 2021-05-18 23:12
Hey @Nitori- 

I followed your steps but wasn't able to reproduce the error.

**Happy path first (add Jira issue key when GitHub PR is created):**

I created an issue in Jira:

<img width="1033" alt="Screen Shot 2021-05-19 at 9 03 55 am" src="https://user-images.githubusercontent.com/37155488/118734390-9c72e700-b881-11eb-8322-00d2d7103521.png">

I then opened a PR with the corresponding issue key TEST-28

<img width="685" alt="Screen Shot 2021-05-19 at 9 04 38 am" src="https://user-images.githubusercontent.com/37155488/118734463-c926fe80-b881-11eb-8fde-53577858f990.png">

And confirmed I could see my PR in issue TEST-28

<img width="966" alt="Screen Shot 2021-05-19 at 9 04 51 am" src="https://user-images.githubusercontent.com/37155488/118734496-d9d77480-b881-11eb-9589-567440fd16b7.png">

**Unhappy path (first create PR with no issue key and then edit to add issue key):**

Created a pr and omitted the issue key TEST-28:

<img width="843" alt="Screen Shot 2021-05-19 at 9 05 26 am" src="https://user-images.githubusercontent.com/37155488/118734547-f8d60680-b881-11eb-8341-f5a7398100e4.png">

At this point I still only have the PR from the happy path example showing up in Jira.

I then edited the PR title and clicked save:

<img width="1018" alt="Screen Shot 2021-05-19 at 9 05 51 am" src="https://user-images.githubusercontent.com/37155488/118734571-0ab7a980-b882-11eb-90ba-ac19ea12595b.png">

Finally I checked issue TEST-28 in Jira and confirmed I now see 2 PRs: the original one I created, and my new PR after editing the PR title.

<img width="958" alt="Screen Shot 2021-05-19 at 9 06 01 am" src="https://user-images.githubusercontent.com/37155488/118734664-376bc100-b882-11eb-9e5e-ac392a547565.png">

To allow to help you, could you send screenshots of the flow as you go through each step?

**Comment by Nitori-** [comment] 2021-05-18 23:14
Ah you know what, I think I might know what the difference is. Does this repo/issue only apply to GitHub.com and JIRA cloud integrations, or does it also apply to self-hosted GitHub Enterprise and self-hosted JIRA?

**Comment by thombergs** [comment] 2021-05-18 23:50
@Nitori- I'm from @rachellerathbone's team at Atlassian and can provide some more context. This integration (the "GitHub for Jira" app) is currently only supporting Github.com and Jira Cloud (i.e. not the self-hosted versions GitHub Enterprise and Jira Server). The integration between Jira Server and GitHub Enterprise is covered by the [DVCS feature in Jira](https://confluence.atlassian.com/jirakb/upgrade-the-jira-dvcs-connector-plugin-in-jira-server-967900869.html), which is independent from the app developed in this repo here. To get that bug sorted out, please raise an issue with the Atlassian support.

**Comment by Nitori-** [comment] 2021-05-18 23:52
Got it! Our use case is with self-hosted everything, so this issue probably doesn't apply to us then, thanks!

**Comment by rachellerathbone** [comment] 2021-05-19 00:03
Thanks for your input @thombergs. @Nitori- confirming you have enough clarification now so that I can close this out.

**Comment by Nitori-** [comment] 2021-05-19 00:04
Yes I think the issue is safe to close from my perspective.

**Comment by rachellerathbone** [comment] 2021-05-19 00:08
Great. Thanks @Nitori-

**Closed by rachellerathbone** 2021-05-19 00:08 UTC
Labels: awaiting response
