### ISSUE TITLE
PRs not displaying in Jira

### ISSUE THREAD

**Issue by nterbogt** [integrations/jira#394] opened 2020-10-13 00:18 UTC
Came across an issue where a PR wouldn't display in Jira.

The PR was created with the github-actions bot as the author and wouldn't be detected. If a real user commented on the PR, it would show up. If a real user changed the status, it would show up. etc etc.

Changing the author of the PR to a real user fixed the issue. We did this by not using ${{ secrets.GITHUB_TOKEN }} in the action and changing that to a custom token for a real user.

It should really just work... however and whoever creates the PR.

**Comment by mat007** [comment] 2020-11-13 10:29
I think I just hit the same issue.
Here is probably the cause for this:
```
    if (context.payload.sender.type === 'Bot') {
      context.log({ noop: 'bot', botId: context.payload.sender.id, botLogin: context.payload.sender.login }, 'Halting futher execution since the sender is a bot');
      return;
    }
```
That’s in https://github.com/integrations/jira/blob/master/lib/github/middleware.js#L63

I don’t understand why a bot should be handled differently than a regular user?

**Comment by VolodymyrFesenko** [comment] 2020-12-10 14:50
This also results in a PR status update not being reported back to Jira if **Bot** merges the PR. Jira shows the linked PR as **open** even though it has been merged.

**Comment by atrigueiro** [comment] 2021-05-14 06:37
Hi all,

We've implemented this feature and it's out in prod! https://github.com/integrations/jira/pull/437

**Closed by atrigueiro** 2021-05-14 06:37 UTC
Labels: P1, bug
