### ISSUE TITLE
Pull requests aren't linked unless the pull request title has the ticket link in it

### ISSUE THREAD

**Issue by jordanfbrown** [integrations/jira#191] opened 2019-04-19 17:41 UTC
In the DVCS integration it seems like JIRA was able to pull in pull requests as long as the ticket number was linked in the pull request message. With this new integration, **it appears to only pick up the pull request if the ticket number is included in the pull request title**.

Wondering if this change was intentional? Or am I missing something?

Here's an example where the ticket link was not included in the PR title and it didn't link it to JIRA. Note that the commit DID link correctly:

![jira-2](https://user-images.githubusercontent.com/467728/56436000-3b861880-628f-11e9-99f5-0392525a91dc.png)

![image](https://user-images.githubusercontent.com/467728/56436056-72f4c500-628f-11e9-998c-39edb5b7d981.png)

And here's an example where the ticket link WAS included in the PR title and it did link the PR correctly:

![jira-3](https://user-images.githubusercontent.com/467728/56436022-4d67bb80-628f-11e9-8d50-63ca5a9b3968.png)

![jira-4](https://user-images.githubusercontent.com/467728/56436025-4f317f00-628f-11e9-871c-aa3910de467d.png)

**Comment by tcbyrd** [comment] 2019-04-19 18:39
Thanks for the excellent write-up @jordanfbrown. I think this is similar to what's being discussed in #119 and we'll work on adding support for it. It was my understanding that DevInfo API was looking for PR titles only. The one question I have is whether the links work in issue comments as well as the body of the PR? I could see this getting noisy if any link to a Jira issue showed up in any issue comment in your Org, but the body of the OP in the PR makes sense.

**Comment by jordanfbrown** [comment] 2019-04-19 22:08
@tcbyrd Ah yes, this does look like a duplicate of #119. Apologies for not reading through the existing issues more carefully. Want me to close this one out?

> The one question I have is whether the links work in issue comments as well as the body of the PR?

Not totally following the question. Are you asking if somebody includes a JIRA ticket link in a Github comment, will it then show up in JIRA? Or am I misunderstanding?

**Comment by tcbyrd** [comment] 2019-04-19 23:05
Yeh exactly. The reason I'm asking is because `issue_comment.body` and `pull_request.body` are 2 separate events we have to listen for. So if you include a link in the `pull_request.body`, which is the first post in a Pull Request, that's one place to look. But if someone puts a link in a comment below the Pull Request, that's a separate event.

So if I include this link in this comment:

https://tcbyrd.atlassian.net/browse/TES-5

Would you expect that link to show up in the `TES-5` issue in Jira, even though someone may just be referencing it from a completely separate issue?

**Comment by jordanfbrown** [comment] 2019-04-22 18:46
Gotcha. In the case of comments made on a PR or in an issue, I personally wouldn't expect it to link back to JIRA. I could see that becoming unwieldy quickly.

**Comment by mrcarriere** [comment] 2019-07-07 19:02
@tcbyrd Chiming is as we miss this feature tremendously -- we would expect the following tickets to be marked as related to a "PR Created" event:

* Mentioned in the PR Body (not the comments, we're in agreement with the current thread so far)
* Mentioned in any commit title OR body in the branch being PR'd

**Comment by hobhouse** [comment] 2020-04-15 17:26
Hi @tcbyrd, just wondering if there was any plan to implement mentions in the PR Body being linked into Jira? It's a feature that I know will be extremely useful at my organisation

**Comment by cfragaa** [comment] 2020-11-25 12:47
hey @tcbyrd, do we have any news around this one?

**Comment by dfan1028** [comment] 2021-01-06 17:21
I used to use clubhouse and it supported both title and link in body for detecting whether or not to link, a bit disappointed jira doesn't have the same.

**Comment by nevir** [comment] 2021-02-12 17:49
This would be extremely helpful. I'd love to be able to reference JIRA issues in the PR/issue body. That way we get easy two way linking, as well.

**Comment by pgrantmartello** [comment] 2021-03-01 15:29
This issue should be closed since it's a duplicate of #119. I can't do the dev work myself, but I might have found the solution to it if someone wants to read my comment on that post and maybe do the testing on their own environment.

**Comment by rachellerathbone** [comment] 2021-05-17 06:34
Closing in favour of #119.

**Closed by rachellerathbone** 2021-05-17 06:34 UTC
Labels: sync
