### ISSUE TITLE
Document exact patterns for branches, commits and pull requests

### ISSUE THREAD

**Issue by adamniedzielski** [integrations/jira#188] opened 2019-04-16 10:25 UTC
Hey 👋I'm not sure if that's the right side of the integration to post this issue. Feel free to close or forward to the Atlassian side.

We are trying to migrate from the DVCS Connector to the new GitHub for Jira app, prompted by an email titled "Action required: Switch to the new GitHub for Jira integration". We're following this article - https://community.atlassian.com/t5/Jira-articles/Everything-you-need-to-know-about-migrating-from-the-DVCS/ba-p/945910

The article mentions that:

> So commits, branches, and pull requests are all being synced as they were and smart commits / workflow triggers work the same way they did previously.

I tried to find out in both GitHub and Atlassian documentation what "the same way they did" precisely means, but didn't manage to find it within 1 hour. Namely, I'm interested what exactly the accepted format is, that I have to put in my branches, commits in pull requests for the integration to work.

Some examples:
1. When using the DVCS Connector a branch name `feature/lief-12155-test-jira` was being correctly linked to the ticket `LIEF-12155` in JIRA. This doesn't work anymore with the new GitHub for Jira app. I have to use `feature/LIEF-12155-test-jira` (please note the capitalised project name).
2. When using the DVCS Connector, a commit title / pull request title `[#LIEF-12155] Test JIRA` was being correctly linked to the ticket `LIEF-12155` in JIRA. This doesn't work anymore with the new GitHub for Jira app. I have to use `[LIEF-12155] Test JIRA` (please notice the missing hash sign).

Based on these two cases I believe that it's beneficial to document the exact patterns that are used to match branches, commits and pull requests to JIRA tickets. Moreover, it would also be helpful to point out the breaking changes in the migration guide.

**Comment by matisnape** [comment] 2019-04-24 09:20
We use naming convention `#ABC-123` and now with this new integration we lost all history in Jira. 
Please, don't treat `#ABC-123` as comments 🙏

**Comment by jnraine** [comment] 2019-08-02 00:20
@adamniedzielski Hello! Thank you for the bug report. I was able to reproduce the bug parsing `[#LIEF-12155]` and have a fix in the pipe (#213).

However, I'm having trouble with the other case:

> When using the DVCS Connector a branch name feature/lief-12155-test-jira was being correctly linked to the ticket LIEF-12155 in JIRA. This doesn't work anymore with the new GitHub for Jira app. I have to use feature/LIEF-12155-test-jira (please note the capitalised project name)

When using DVCS, I'm not able to reproduce the behaviour you describe. Do the steps below match your workflow?

1. [Configure DVCS Connector](https://confluence.atlassian.com/adminjiracloud/connect-jira-cloud-to-github-814188429.html#ConnectJiraCloudtoGitHub-ConnectaGitHubEnterpriseaccounttotrue) and add a repository
2. Create a new branch named `feature/leif-1-something-good`
3. Push branch to GitHub
3. Open LEIF-1 in JIRA

After these steps, no branches appear under the Development sidebar. Do you see something different with your instance?

**Comment by jnraine** [comment] 2019-08-08 20:48
@adamniedzielski @matisnape Hello! :wave:

Some good news: commits and pull request titles that reference issue keys like `[#JRA-123]` or `#JRA-123]` should now be correctly associated to those issues in Jira.

Branches that include lower case issue keys—like `feature/lief-12155-test-jira `—are not yet support but I've opened #220 to investigate it. Stay tuned!

**Comment by rachellerathbone** [comment] 2021-05-17 06:33
Closing as behaviour is different from that stated in original description. Also, my team is looking into improving this experience for users so they are not confined to only using uppercase letters.

**Closed by rachellerathbone** 2021-05-17 06:33 UTC
Labels: bug
